# 2.1 Data Manipulation 

In [1]:
import torch

In [5]:
x = torch.arange(12,dtype = torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [6]:
x.numel()

12

In [7]:
x.shape

torch.Size([12])

In [9]:
x = x.reshape([3,4]) # x.reshape([3,-1]) or x.reshape([-1,4])
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [11]:
torch.zeros([2,3,4])

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones([2,3,4])

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [14]:
torch.rand([2,3,4])

tensor([[[0.6922, 0.4296, 0.8058, 0.7119],
         [0.1836, 0.0728, 0.3549, 0.4821],
         [0.2651, 0.8654, 0.2976, 0.2603]],

        [[0.6068, 0.5840, 0.3182, 0.2139],
         [0.8348, 0.8343, 0.9720, 0.7006],
         [0.2547, 0.2830, 0.3248, 0.6117]]])

In [16]:
#condstruct by list
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [19]:
# indexing and slicing 
X = torch.arange(12).reshape([3,4])
X,X[-1],X[1:3]

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [21]:
X[1,2] = 14
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5, 14,  7],
        [ 8,  9, 10, 11]])

In [22]:
X[:2,] = 12
X

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

In [23]:
x,torch.exp(x)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[1.0000e+00, 2.7183e+00, 7.3891e+00, 2.0086e+01],
         [5.4598e+01, 1.4841e+02, 4.0343e+02, 1.0966e+03],
         [2.9810e+03, 8.1031e+03, 2.2026e+04, 5.9874e+04]]))

In [24]:
x = torch.tensor([1,2,3,4])
y = torch.tensor([1,2,3,4])
x + y, x - y, x * y, x**y #by elementary

(tensor([2, 4, 6, 8]),
 tensor([0, 0, 0, 0]),
 tensor([ 1,  4,  9, 16]),
 tensor([  1,   4,  27, 256]))

In [27]:
x * y.T,x @ y.T # 一维向量的转置还是一维向量

(tensor([ 1,  4,  9, 16]), tensor(30))

tensor([1, 2, 3, 4])

In [30]:
#对于维度进行cat时，可以理解为指定维度的数量相加
x = torch.arange(24).reshape([2,3,4])
y = torch.arange(24).reshape([2,3,4])
torch.cat((x,y),dim=0).shape,torch.cat((x,y),dim=1).shape,torch.cat((x,y),dim=2).shape
#4,3,4;2,6,4;2,3,8

(torch.Size([4, 3, 4]), torch.Size([2, 6, 4]), torch.Size([2, 3, 8]))

In [31]:
x == y

tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]],

        [[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])

In [33]:
# Broadcasting是非常重要的功能，在低维的时候好理解，但在高纬时就很抽象了
a = torch.arange(3).reshape((3,1)) #tuple
b = torch.arange(2).reshape([1,2]) #list
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [ ]:
# saving memory 
# in place操作，但是很奇怪的一点是在实际使用的额时候应用的不多呢，文中描述的形式
# 另一种in place的方式是add_()这种形式。

In [34]:
# 可以从numpy直接转换成tensor，这一点在本章的最开始也说了，现有的机器学习框架是在numpy的基础上实现的，
# 额外添加的功能就是自动求导，使其可以更方便的计算梯度
A = X.numpy()
B = torch.from_numpy(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

# Data Processing 

这部分的内容跳过了，主要讲的pandas的使用方法，或者说讲的是对于野生的数据集要怎么处理，因为已经有了pandas的使用经验，所以不再赘述。

# Liner Alhebra